package fr.benjimania74.daj.gateway.event;

import lombok.Getter;

import java.util.EnumSet;

public enum Events {
    READY("READY", ReadyEvent.class),

    APPLICATION_COMMAND_PERMISSIONS_UPDATE("APPLICATION_COMMAND_PERMISSIONS_UPDATE", null),

    TYPING_START("TYPING_START", null),

    USER_UPDATE("USER_UPDATE", null),

    WEBHOOKS_UPDATE("WEBHOOKS_UPDATE", null),


    AUTO_MODERATION_RULE_CREATE("AUTO_MODERATION_RULE_CREATE", null),
    AUTO_MODERATION_RULE_UPDATE("AUTO_MODERATION_RULE_UPDATE", null),
    AUTO_MODERATION_RULE_DELETE("AUTO_MODERATION_RULE_DELETE", null),
    AUTO_MODERATION_ACTION_EXECUTION("AUTO_MODERATION_ACTION_EXECUTION", null),


    CHANNEL_CREATE("CHANNEL_CREATE", null),
    CHANNEL_UPDATE("CHANNEL_UPDATE", null),
    CHANNEL_DELETE("CHANNEL_DELETE", null),
    CHANNEL_PINS_UPDATE("CHANNEL_PINS_UPDATE", null),
    THREAD_CREATE("THREAD_CREATE", null),
    THREAD_UPDATE("THREAD_CREATE", null),
    THREAD_DELETE("THREAD_DELETE", null),
    THREAD_LIST_SYNC("THREAD_LIST_SYNC", null),
    THREAD_MEMBER_UPDATE("THREAD_MEMBER_UPDATE", null),
    THREAD_MEMBERS_UPDATE("THREAD_MEMBERS_UPDATE", null),
    STAGE_INSTANCE_CREATE("STAGE_INSTANCE_CREATE", null),
    STAGE_INSTANCE_UPDATE("STAGE_INSTANCE_CREATE", null),
    STAGE_INSTANCE_DELETE("STAGE_INSTANCE_DELETE", null),
    VOICE_CHANNEL_EFFECT_SEND("VOICE_CHANNEL_EFFECT_SEND", null),
    VOICE_STATE_UPDATE("VOICE_STATE_UPDATE", null),
    VOICE_SERVER_UPDATE("VOICE_SERVER_UPDATE", null),


    ENTITLEMENT_CREATE("ENTITLEMENT_CREATE", null),
    ENTITLEMENT_UPDATE("ENTITLEMENT_UPDATE", null),
    ENTITLEMENT_DELETE("ENTITLEMENT_DELETE", null),


    GUILD_CREATE("GUILD_CREATE", null),
    GUILD_UPDATE("GUILD_UPDATE", null),
    GUILD_DELETE("GUILD_DELETE", null),
    GUILD_AUDIT_LOG_ENTRY_CREATE("GUILD_AUDIT_LOG_ENTRY_CREATE", null),
    GUILD_BAN_ADD("GUILD_BAN_ADD", null),
    GUILD_BAN_REMOVE("GUILD_BAN_REMOVE", null),
    GUILD_EMOJIS_UPDATE("GUILD_EMOJIS_UPDATE", null),
    GUILD_STICKERS_UPDATE("GUILD_STICKERS_UPDATE", null),
    GUILD_INTEGRATIONS_UPDATE("GUILD_INTEGRATIONS_UPDATE", null),
    GUILD_MEMBER_ADD("GUILD_MEMBER_ADD", null),
    GUILD_MEMBER_UPDATE("GUILD_MEMBER_UPDATE", null),
    GUILD_MEMBER_REMOVE("GUILD_MEMBER_REMOVE", null),
    GUILD_ROLE_CREATE("GUILD_ROLE_CREATE", null),
    GUILD_ROLE_DELETE("GUILD_ROLE_DELETE", null),
    GUILD_ROLE_UPDATE("GUILD_ROLE_UPDATE", null),
    GUILD_MEMBERS_CHUNK("GUILD_MEMBERS_CHUNK", null),
    GUILD_SCHEDULED_EVENT_CREATE("GUILD_SCHEDULED_EVENT_CREATE", null),
    GUILD_SCHEDULED_EVENT_UPDATE("GUILD_SCHEDULED_EVENT_UPDATE", null),
    GUILD_SCHEDULED_EVENT_DELETE("GUILD_SCHEDULED_EVENT_DELETE", null),
    GUILD_SCHEDULED_EVENT_USER_ADD("GUILD_SCHEDULED_EVENT_USER_ADD", null),
    GUILD_SCHEDULED_EVENT_USER_REMOVE("GUILD_SCHEDULED_EVENT_USER_REMOVE", null),

    INVITE_CREATE("INVITE_CREATE", null),
    INVITE_DELETE("INVITE_DELETE", null),

    PRESENCE_UPDATE("PRESENCE_UPDATE", null),


    INTEGRATION_CREATE("INTEGRATION_CREATE", null),
    INTEGRATION_UPDATE("INTEGRATION_UPDATE", null),
    INTEGRATION_DELETE("INTEGRATION_DELETE", null),

    INTERACTION_CREATE("INTERACTION_CREATE", null),

    MESSAGE_CREATE("MESSAGE_CREATE", null),
    MESSAGE_UPDATE("MESSAGE_UPDATE", null),
    MESSAGE_DELETE("MESSAGE_DELETE", null),
    MESSAGE_DELETE_BULK("MESSAGE_DELETE_BULK", null),
    MESSAGE_REACTION_ADD("MESSAGE_REACTION_ADD", null),
    MESSAGE_REACTION_REMOVE("MESSAGE_REACTION_REMOVE", null),
    MESSAGE_REACTION_REMOVE_ALL("MESSAGE_REACTION_REMOVE_ALL", null),
    MESSAGE_REACTION_REMOVE_EMOJI("MESSAGE_REACTION_REMOVE_EMOJI", null),
    MESSAGE_POLL_VOTE_ADD("MESSAGE_POLL_VOTE_ADD", null),
    MESSAGE_POLL_VOTE_REMOVE("MESSAGE_POLL_VOTE_REMOVE", null),


    NONE("NONE", null);

    @Getter
    private final String name;

    @Getter
    private final Class<? extends Event> eventClass;

    Events(String name, Class<? extends Event> eventClass){
        this.name = name;
        this.eventClass = eventClass;
    }

    public static Events getEvent(String name){
        for(Events e : EnumSet.allOf(Events.class)){
            if(e.name.equalsIgnoreCase(name)){
                return e;
            }
        }
        return NONE;
    }

    @Override
    public String toString(){return getName();}
}
